export const ADD_SUBJECT = "ADD_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const RENAME_SUBJECT = "RENAME_SUBJECT";
export const SET_SELECTED_SUBJECT = "SET_SELECTED_SUBJECT";

export const ADD_INSTANCE = "ADD_INSTANCE";
export const DELETE_INSTANCE = "DELETE_INSTANCE";

export const ADD_TO_INSTANCE_STORE = "ADD_TO_INSTANCE_STORE";
export const DELETE_FROM_INSTANCE_STORE = "DELETE_FROM_INSTANCE_STORE";

export const ADD_KEYVALUE = "ADD_KEYVALUE";
export const DELETE_KEYVALUE = "DELETE_KEYVALUE";
