export const ADD_SUBJECT = "ADD_SUBJECT";
export const CREATE_SUBJECT = "CREATE_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const RENAME_SUBJECT = "RENAME_SUBJECT";
export const SET_SELECTED_SUBJECT_NAME = "SET_SELECTED_SUBJECT_NAME";

export const ADD_CRITERION = "ADD_CRITERION";
export const DELETE_CRITERION = "DELETE_CRITERION";
export const EDIT_CRITERION = "EDIT_CRITERION";

export const ADD_INSTANCE = "ADD_INSTANCE";
export const DELETE_INSTANCE = "DELETE_INSTANCE";
export const RENAME_INSTANCE = "RENAME_INSTANCE";
export const SET_SELECTED_INSTANCE_NAME = "SET_SELECTED_INSTANCE_NAME";

export const ADD_KEYVALUE = "ADD_KEYVALUE";
export const DELETE_KEYVALUE = "DELETE_KEYVALUE";
export const EDIT_KEYVALUE = "EDIT_KEYVALUE";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
